### ISSUE TITLE
Working on the same functionality

### ISSUE THREAD

**Issue by Sicos1977** [logankp/Deliverance#1]
Hi,

It seems that we are working on the same functionality... reading and writing MSG files with C# .NET.... the only thing is that I'm somewhat further ahead in implementing functionality.

You can find my project overhere (also used OpenMCDF) --> https://github.com/Sicos1977/MSGWriter
And you can find an MSGReader overhere (That uses COM) --> https://github.com/Sicos1977/MSGReader

**Comment by logankp** [comment]
I took a look at both. I support reading MSGs without using COM, but I still need to work on writing. It appears that you have two separate projects for reading and writing?

**Comment by Sicos1977** [comment]
My main goal is also to support reading with the MSGWriter. I just needed a new name so MSGWriter was the obvious choice. But first I finish the writing part and then also change the MSGWriter to support reading. Writing MSG files is the hard part because MSG is a rather complex format to produce.

Not to be blunt but your MSG reader is far from complete because you don't support HTML that is encapsulated in RTF. Most of the MSG files are this way... and you only support the IPM.Note format. MSG has many more formats... like appointments, sticky notes... etc.. etc...

**Comment by logankp** [comment]
Oh I'm aware. I actually began writing it for one specific use case, which was reading the IPM.Note format. I've been meaning to support more formats, but I haven't had much time.

**Comment by Sicos1977** [comment]
I know the problem... everyone (including managers) think that writing a tool that looks rather simple from the outside (It only reads an e-mail) is done in a few days. But they never see the complexity that is behind that rather simple thing :-)
