### ISSUE TITLE
Working MSG writer

### ISSUE THREAD

**Issue by Sicos1977** [logankp/Deliverance#2]
Hi,

If you ever need a working MSG writer... I managed to get my version working as intended :-) ... still beta but it works ... https://github.com/Sicos1977/MSGWriter

It was an awful lot of work... the msg format is way to complex if you ask me

**Comment by logankp** [comment]
Awesome! I'll have to play around with it.

**Comment by Sicos1977** [comment]
I still have some issues with adding the recipients... for some reason that doesn't always work.... still have to figure that out.

**Comment by Sicos1977** [comment]
The recipients are now also working
